### ISSUE TITLE
Cannot find module __bundle_analysis.json

### ISSUE THREAD

**Issue by isaachinman** [hashicorp/nextjs-bundle-analysis#1]
Thanks @jescalan for this fantastic project!

Trying to get up and running here, and hitting this error:

```sh
> npx nextjs-bundle-analysis generate

Cannot find module '~/my-project/.next/analyze/__bundle_analysis.json'
Require stack:
- ~/.npm/_npx/38403/lib/node_modules/nextjs-bundle-analysis/compare.js
```

I think we'll need to conditionally `require` [here](https://github.com/hashicorp/nextjs-bundle-analysis/blob/main/compare.js#L9). Thoughts?

**Comment by jescalan** [comment]
Got to testing it before I did! I'll have this patched for sure, though the error makes no sense at all to me since it comes from an entirely different script 🤔

**Comment by jescalan** [comment]
oh wow npx just runs all executables 🤦

**Comment by jescalan** [comment]
Ok this one is resolved in the latest release
