### ISSUE TITLE
Publish a new version? 🙏 

### ISSUE THREAD

**Issue by RyanMcDonald** [hashicorp/nextjs-bundle-analysis#25]
I'm looking to take advantage of the new `minimumChangeThreshold` option, but it isn't included in the latest version.

**Comment by pcmaffey** [comment]
FYI can replace `npx -p nextjs-bundle-analysis` with `npx -yes -p github:hashicorp/nextjs-bundle-analysis` to use the latest changes. Was scratching my head why the `minimumChangeThreshold` wasn't working...

**Comment by RyanMcDonald** [comment]
Thank you! What does `-yes` do in this case? I can't find any documentation on that.

**Comment by pcmaffey** [comment]
It default answers `y` to the first prompt asked when running the `compare` script.

**Comment by gthb** [comment]
> FYI can replace `npx -p nextjs-bundle-analysis` with `npx -yes -p github:hashicorp/nextjs-bundle-analysis` to use the latest changes. Was scratching my head why the `minimumChangeThreshold` wasn't working...

That fails for me in Node v16.18.0, silently, dumping me into a shell:

```
$ npx -yes -p github:hashicorp/nextjs-bundle-analysis

Entering npm script environment at location:
/Users/gthb/git/GRID-client
Type 'exit' or ^D when finished

sh-3.2$ 
```

Any clue why?

(And any reason why this hasn't been released yet?)

**Comment by gthb** [comment]
> Any clue why?

Oh, it's because the `report` (and `compare`) at the end was missing (I just dumbly copy-pasted from the above) ... the behavior when no argument is supplied is just super confusing. :)
