### ISSUE TITLE
update find-comment string

### ISSUE THREAD

**Issue by Entkenntnis** [hashicorp/nextjs-bundle-analysis#52]
https://github.com/hashicorp/nextjs-bundle-analysis/pull/44 has changed the comment string to include the repo name.

This is currently breaking the find-comment action in the workflow.

**Comment by jzxhuang** [comment]
+1, this actually broke all existing usage of the action

An easy fix would be to update the template:
```
body-includes: '<!-- __NEXTJS_BUNDLE -->'
```

to

```
body-includes: '<!-- __NEXTJS_BUNDLE_<your-package.json-name> -->'
```

I just made this change on our team's GH action.

However, a better fix would probably be to make the monorepo support changes from #44  a manual opt-in? 

cc @BRKalow @dstaley

**Comment by dstaley** [comment]
Hi @Entkenntnis and @jzxhuang!

We're working on a patch release with an updated workflow that no longer relies on the comment string which should be more reliable. In the meantime, you have three options (in order of preference):

1. Pin the version of `nextjs-bundle-analysis` used by running `npm install --save-dev nextjs-bundle-analysis@0.4.0`. This ensures that future breaking changes do not break your workflow.
2. Update all instances of `npx -p nextjs-bundle-analysis` in your workflow file to use an explicit version (`npx -p nextjs-bundle-analysis@0.4.0`).
3. Update your workflow's `body-includes` setting to use the string `<!-- __NEXTJS_BUNDLE_<your-package.json-name> -->` as @jzxhuang has done.

A future patch version will migrate to using [sticky-pull-request-comment](https://github.com/marocchino/sticky-pull-request-comment), which will no longer require that we manually embed an identifier into the comment. You can upgrade right now by replacing the Find, Create, and Update steps with the following:

```yml
- name: Comment
  uses: marocchino/sticky-pull-request-comment@v2
  with:
    header: next-touched-pages
    message: ${{ steps.get-comment-body.outputs.body }}
```

**Comment by jzxhuang** [comment]
@dstaley awesome, thanks for the quick update! I didn't realize adding the dep would also affect what the GH action pulled, but I guess that makes a lot of sense. Maybe consider adding a short blurb to the README recommending folks to pin the version of the script as part of the installation steps? 🤷 

The sticky-pull-request-comment action looks dope :)

**Comment by zomars** [comment]
So this is why our workflow was spamming bundle comments everywhere. Thanks for the update!

**Comment by gaearon** [comment]
@dstaley 

>Update all instances of npx -p nextjs-bundle-analysis in your workflow file to use an explicit version (npx -p nextjs-bundle-analysis@0.4.0).

Shouldn't this be done directly in https://github.com/hashicorp/nextjs-bundle-analysis/blob/main/template.yml? If people copy it (like we did), it's really easy to miss that it opts you into breaking changes. I would suggest to change the template to use a fixed version, and then bump it up manually as you do new releases.

**Comment by votemike** [comment]
Is there any update on this?
The new version was mentioned in April.
