### ISSUE TITLE
How can I use with pnpx

### ISSUE THREAD

**Issue by dukeofsoftware** [hashicorp/nextjs-bundle-analysis#53]
How can I use with pnpx

![image](https://user-images.githubusercontent.com/89215036/231871711-77f6f9e2-a9c7-4d63-bdcd-43464819f4de.png)

**Comment by Dremora** [comment]
`pnpm --package=nextjs-bundle-analysis dlx generate`

Note that `pnpx` is the same is `pnpm dlx`, but we need to use the full version in order to choose the `generate` binary.

**Comment by dukeofsoftware** [comment]
thanks!

**Comment by dukeofsoftware** [comment]
thanks
