### ISSUE TITLE
Edit comment instead of adding a new comment

### ISSUE THREAD

**Issue by mlenser** [hashicorp/nextjs-bundle-analysis#58]
The action currently adds a new comment every time commits are pushed to the branch.

Can the action instead edit the existing comment instead of adding another comment? Similar to how Vercel preview environments does (perhaps they expose their action?).

**Comment by BRKalow** [comment]
Hi there, a solution can be found here: https://github.com/hashicorp/nextjs-bundle-analysis/issues/52#issuecomment-1507644855

**Comment by mlenser** [comment]
Thanks for the super quick update and for the great work! I look forward to the new release with `sticky-pull-request-comment`!
