### ISSUE TITLE
Using working directory but failing in step Compare with base branch bundle

### ISSUE THREAD

**Issue by maapteh** [hashicorp/nextjs-bundle-analysis#8]
Im using a working directory, which is used for every run. During "Upload bundle" i had to add it there too:

` path: ./apps/FOO/.next/analyze/__bundle_analysis.json`

But now it fails in the comparison step and i have no clue why...

Download base branch bundle stats:
```
==> Conclusion: success
==> Branch: main
==> RunID: 1290529608
==> Artifact: 97934011
==> Downloading: bundle.zip (288 B)
  inflating: .next/analyze/base/bundle/__bundle_analysis.json
```

So it seems to inflate something. No clue where, also used our working directory there, no success.

Error in next step
```
Run ls -laR .next/analyze/base && npx -p nextjs-bundle-analysis compare
ls: cannot access '.next/analyze/base': No such file or directory
```

**Comment by maapteh** [comment]
wrong dir used

**Comment by Megrax** [comment]
I had the same problem. Solved by adding my nextjs app's root dir before the path.
e.g.

```diff
workflow: nextjs_bundle_analysis.yml
branch: ${{ github.event.pull_request.base.ref }}
- path: .next/analyze/base
+ path: ./frontend/.next/analyze/base
```
